-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: ede02bf2a342f2c3c411ccfe5783bc15f7fcd3cf4ee40863f9794f649aa41667
-- Atlas versioned migration artifact (atlas.sum is out of scope)
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

CREATE TABLE orders (id integer PRIMARY KEY);
