-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: 609a0527ef8d2e045f7c9ddb8d47e233e8f3e1445a41e1261c28a3d3de834bae
-- Atlas versioned migration artifact (atlas.sum is out of scope)
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

CREATE TABLE orders (id integer PRIMARY KEY);
