-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: f7262045d97568701b0f33e7b8cc5c4da72e009ee5edc25a68fe41a2d578de96
-- Atlas versioned migration artifact (atlas.sum is out of scope)
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

CREATE TABLE orders (id integer PRIMARY KEY);
