-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: 70b0d18451eb157b9e5f099320822e43f78b103767e9cb8a878994cd1f76b390
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

-- +goose Up
CREATE TABLE accounts (id integer PRIMARY KEY);
ALTER TABLE accounts ADD COLUMN balance numeric NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE accounts DROP COLUMN IF EXISTS balance;
DROP TABLE IF EXISTS accounts CASCADE;
