-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: b8549a738434265c3cfda1dd38edb26f95440c06d50a95c582c9baa57321d33e
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

-- +goose Up
CREATE TABLE accounts (id integer PRIMARY KEY);
ALTER TABLE accounts ADD COLUMN balance numeric NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE accounts DROP COLUMN IF EXISTS balance;
DROP TABLE IF EXISTS accounts CASCADE;
