-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: a38f6a7a88228c0e1bb7781e4f25f280a154339be12e325409a9208b565f8575
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

-- +goose Up
DROP TABLE legacy_users CASCADE;

-- Down migration omitted: plan contains irreversible changes (DROP_TABLE on table legacy_users)
