-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: cea82e4ac8399d57a971a56a2a9818204aa05309db4df0e8a96c027fb7a14129
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

-- +goose Up
CREATE TABLE accounts (id integer PRIMARY KEY);
ALTER TABLE accounts ADD COLUMN balance numeric NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE accounts DROP COLUMN IF EXISTS balance;
DROP TABLE IF EXISTS accounts CASCADE;
