-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: b7ba16bd1f81e4069466fa3b449c4093d6d5592dd7b01e70995cd6565a0f3f5b
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

-- +goose Up
DROP TABLE legacy_users CASCADE;

-- Down migration omitted: plan contains irreversible changes (DROP_TABLE on table legacy_users)
