-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: cd04aa123b98a5857401b1d096d946a96455e9f2681e50ef293e0792ea91d817
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

-- +goose Up
DROP TABLE legacy_users CASCADE;

-- Down migration omitted: plan contains irreversible changes (DROP_TABLE on table legacy_users)
