-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: bc335a4149f3406802c0781e7590fb182d62bd5e83b57c247fbffb79a5913e9e
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

CREATE TABLE users (id integer PRIMARY KEY, name text NOT NULL);

-- grizzle:notx
CREATE INDEX CONCURRENTLY idx_users_name ON users (name);
