-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: 0b9acb93e8e8cc891caa07e2b4352d15314c13f09095d941453a307bd111a813
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

CREATE TABLE users (id integer PRIMARY KEY, name text NOT NULL);

-- grizzle:notx
CREATE INDEX CONCURRENTLY idx_users_name ON users (name);
