-- Generated by Grizzle v0.1.0 (https://github.com/muandane/grizzle)
-- Plan Hash: 915e3bf846fc53b5f946b7d929ef6230355eed797c4ccee87e8889693123c2f0
-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.

CREATE TABLE users (id integer PRIMARY KEY, name text NOT NULL);

-- grizzle:notx
CREATE INDEX CONCURRENTLY idx_users_name ON users (name);
