package main

import (
	"context"
	"database/sql"
	_ "embed"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/muandane/grizzle"
	"github.com/muandane/grizzle/examples/sqlc-workflow/db"
)

//go:embed schema.sql
var schemaSQL string

func main() {
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		dsn = "postgres://postgres:password@localhost:5432/myapp?sslmode=disable"
	}

	targetSchema := os.Getenv("PG_SCHEMA")
	if targetSchema != "" {
		if strings.Contains(dsn, "?") {
			dsn = fmt.Sprintf("%s&search_path=%s", dsn, targetSchema)
		} else {
			dsn = fmt.Sprintf("%s?search_path=%s", dsn, targetSchema)
		}
	}

	sqlDB, err := sql.Open("pgx", dsn)
	if err != nil {
		log.Fatalf("invalid database connection: %v", err)
	}
	defer func() { _ = sqlDB.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()

	if err := sqlDB.PingContext(ctx); err != nil {
		log.Fatalf("database unreachable: %v", err)
	}

	// 1. In-process declarative schema automigration with Grizzle
	log.Println("Applying schema synchronization from shared schema.sql...")
	err = grizzle.Sync(ctx, sqlDB, grizzle.Options{
		TargetSchema:  targetSchema,
		SchemaSQL:     schemaSQL,
		AllowDrop:     false, // Default-deny drops in production
		StrictScope:   true,  // Protect unmanaged tables
		IncludeTables: []string{"organizations", "users"},
	})
	if err != nil {
		log.Fatalf("grizzle schema sync failed: %v", err)
	}

	// 2. Execute type-safe queries generated by sqlc
	queries := db.New(sqlDB)

	orgName := fmt.Sprintf("Acme Corp %d", time.Now().UnixNano())
	org, err := queries.CreateOrganization(ctx, orgName)
	if err != nil {
		log.Fatalf("creating org failed: %v", err)
	}
	log.Printf("Created organization %q (id=%d)", org.Name, org.ID)

	userEmail := fmt.Sprintf("dev_%d@acme.com", time.Now().UnixNano())
	user, err := queries.CreateUser(ctx, db.CreateUserParams{
		OrgID:    org.ID,
		Email:    userEmail,
		FullName: "Grizzle Developer",
	})
	if err != nil {
		log.Fatalf("creating user failed: %v", err)
	}
	log.Printf("Created user %q (id=%d, org_id=%d)", user.Email, user.ID, user.OrgID)

	fetched, err := queries.GetUserByEmail(ctx, userEmail)
	if err != nil {
		log.Fatalf("fetching user failed: %v", err)
	}
	log.Printf("Successfully fetched user by email: %s", fetched.FullName)
}
