-- schema.sql — desired schema state for the catalog-sync example.
--
-- The event-trigger function below must exist before the CatalogSQL sync
-- runs: Grizzle refuses to create an event trigger whose function is
-- missing (see examples/catalog-sync/catalog.sql).

CREATE TABLE docs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  body text NOT NULL
);

CREATE FUNCTION log_ddl() RETURNS event_trigger
LANGUAGE plpgsql AS $$
BEGIN
  -- Real deployments would record the DDL event somewhere durable.
  RAISE NOTICE 'ddl event: % %', TG_EVENT, TG_TAG;
END;
$$;
