package export

import (
	"fmt"
	"regexp"
	"slices"
	"strings"
	"time"

	"github.com/muandane/grizzle/internal/plan"
)

// Format represents the target format for migration export.
type Format string

const (
	// FormatSQL emits a standard SQL file with transactional and non-transactional annotations.
	FormatSQL Format = "sql"
	// FormatGoose emits a Goose-compatible migration file with Up/Down sections.
	FormatGoose Format = "goose"
	// FormatAtlas emits an Atlas-compatible SQL migration file.
	FormatAtlas Format = "atlas"
)

// Artifact represents a generated migration file ready to be written to disk.
type Artifact struct {
	Filename string
	Content  string
}

// Export generates migration artifacts for the plan in the requested format.
func Export(p *plan.Plan, format Format, version string, timestamp time.Time) ([]Artifact, error) {
	if p == nil {
		return nil, fmt.Errorf("grizzle: plan cannot be nil")
	}
	if version == "" {
		version = "dev"
	}
	if timestamp.IsZero() {
		timestamp = time.Now().UTC()
	}

	tsStr := timestamp.Format("20060102150405")
	filename := fmt.Sprintf("%s_migration.sql", tsStr)

	switch format {
	case FormatSQL:
		return []Artifact{{
			Filename: filename,
			Content:  renderSQL(p, version),
		}}, nil

	case FormatGoose:
		return []Artifact{{
			Filename: filename,
			Content:  renderGoose(p, version),
		}}, nil

	case FormatAtlas:
		return []Artifact{{
			Filename: filename,
			Content:  renderAtlas(p, version),
		}}, nil

	default:
		return nil, fmt.Errorf("grizzle: unsupported export format %q (supported: sql, goose, atlas)", format)
	}
}

func renderHeader(p *plan.Plan, version string, extra ...string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- Generated by Grizzle %s (https://github.com/muandane/grizzle)\n", version)
	fmt.Fprintf(&b, "-- Plan Hash: %s\n", p.Hash())
	for _, line := range extra {
		fmt.Fprintf(&b, "-- %s\n", line)
	}
	b.WriteString("-- WARNING: This is an exported migration artifact. Never edit directly or re-import into Grizzle.\n\n")
	return b.String()
}

func renderSQL(p *plan.Plan, version string) string {
	var b strings.Builder
	b.WriteString(renderHeader(p, version))

	for i, step := range p.Steps {
		if step.NonTx {
			b.WriteString("-- grizzle:notx\n")
		}
		b.WriteString(strings.TrimSpace(step.SQL))
		if i < len(p.Steps)-1 {
			b.WriteString("\n\n")
		} else {
			b.WriteString("\n")
		}
	}
	return b.String()
}

func renderAtlas(p *plan.Plan, version string) string {
	var b strings.Builder
	b.WriteString(renderHeader(p, version, "Atlas versioned migration artifact (atlas.sum is out of scope)"))

	for i, step := range p.Steps {
		b.WriteString(strings.TrimSpace(step.SQL))
		if i < len(p.Steps)-1 {
			b.WriteString("\n\n")
		} else {
			b.WriteString("\n")
		}
	}
	return b.String()
}

func renderGoose(p *plan.Plan, version string) string {
	var b strings.Builder
	b.WriteString(renderHeader(p, version))

	b.WriteString("-- +goose Up\n")
	hasNonTx := false
	for _, s := range p.Steps {
		if s.NonTx {
			hasNonTx = true
			break
		}
	}
	if hasNonTx {
		b.WriteString("-- +goose NO TRANSACTION\n")
	}

	for _, step := range p.Steps {
		b.WriteString(strings.TrimSpace(step.SQL))
		b.WriteString("\n")
	}

	// Check if all steps are reversible
	var reversible = true
	var failStep plan.Step
	for _, s := range p.Steps {
		if !isStepReversible(s) {
			reversible = false
			failStep = s
			break
		}
	}

	b.WriteString("\n")
	if reversible {
		b.WriteString("-- +goose Down\n")
		revSteps := slices.Clone(p.Steps)
		slices.Reverse(revSteps)
		for _, s := range revSteps {
			b.WriteString(reverseStepSQL(s))
			b.WriteString("\n")
		}
	} else {
		fmt.Fprintf(&b, "-- Down migration omitted: plan contains irreversible changes (%s on table %s)\n", failStep.Type, failStep.Table)
	}

	return b.String()
}

func isStepReversible(s plan.Step) bool {
	switch s.Type {
	case plan.ChangeCreateTable, plan.ChangeAddColumn, plan.ChangeCreateIndex, plan.ChangeAddFK, plan.ChangeAddCheck, plan.ChangeRenameColumn, plan.ChangeAttachPartition,
		plan.ChangeCreatePolicy, plan.ChangeEnableRLS, plan.ChangeDisableRLS, plan.ChangeForceRLS, plan.ChangeNoForceRLS,
		plan.ChangeCreateFunction, plan.ChangeCreateAggregate, plan.ChangeCreateTrigger, plan.ChangeCreateView, plan.ChangeRefreshMatView,
		plan.ChangeCommentTable, plan.ChangeCommentColumn:
		return true
	default:
		// ChangeCreateExtension is intentionally irreversible: uninstalling an
		// extension may destroy data generated by its types/operators.
		return false
	}
}

var (
	indexNameRegex = regexp.MustCompile(`(?i)CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?(?:["'` + "`" + `]?[\w\.]*["'` + "`" + `]?\.)?["'` + "`" + `]?([\w]+)["'` + "`" + `]?`)
	fkNameRegex    = regexp.MustCompile(`(?i)CONSTRAINT\s+["'` + "`" + `]?([\w]+)["'` + "`" + `]?\s+FOREIGN\s+KEY`)
)

func reverseStepSQL(s plan.Step) string {
	switch s.Type {
	case plan.ChangeCreateTable:
		return fmt.Sprintf("DROP TABLE IF EXISTS %s CASCADE;", s.Table)

	case plan.ChangeAddColumn:
		colName := s.Column
		if colName == "" {
			// Extract from SQL: ADD COLUMN [name]
			re := regexp.MustCompile(`(?i)ADD\s+COLUMN\s+["'` + "`" + `]?([\w]+)["'` + "`" + `]?`)
			if m := re.FindStringSubmatch(s.SQL); len(m) == 2 {
				colName = m[1]
			}
		}
		return fmt.Sprintf("ALTER TABLE %s DROP COLUMN IF EXISTS %s;", s.Table, colName)

	case plan.ChangeCreateIndex:
		idxName := ""
		if m := indexNameRegex.FindStringSubmatch(s.SQL); len(m) == 2 {
			idxName = m[1]
		}
		if idxName != "" {
			return fmt.Sprintf("DROP INDEX IF EXISTS %s;", idxName)
		}
		return "-- DROP INDEX unknown;"

	case plan.ChangeAddFK:
		fkName := ""
		if m := fkNameRegex.FindStringSubmatch(s.SQL); len(m) == 2 {
			fkName = m[1]
		}
		if fkName != "" {
			return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT IF EXISTS %s;", s.Table, fkName)
		}
		return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT;", s.Table)

	case plan.ChangeAddCheck:
		checkName := plan.ExtractConstraintName(s.SQL, "ADD")
		if checkName != "" {
			return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT IF EXISTS %s;", s.Table, checkName)
		}
		return fmt.Sprintf("ALTER TABLE %s DROP CONSTRAINT;", s.Table)

	case plan.ChangeRenameColumn:
		return fmt.Sprintf("ALTER TABLE %s RENAME COLUMN %s TO %s;", s.Table, s.Column, s.OldColumn)

	case plan.ChangeAttachPartition:
		return fmt.Sprintf("ALTER TABLE %s DETACH PARTITION %s;", s.ParentTable, s.Table)

	case plan.ChangeCreatePolicy:
		polName := ""
		if m := policyNameRegex.FindStringSubmatch(s.SQL); len(m) == 2 {
			polName = m[1]
		}
		return fmt.Sprintf("DROP POLICY IF EXISTS %s ON %s;", polName, s.Table)

	case plan.ChangeEnableRLS:
		return fmt.Sprintf("ALTER TABLE %s DISABLE ROW LEVEL SECURITY;", s.Table)
	case plan.ChangeDisableRLS:
		return fmt.Sprintf("ALTER TABLE %s ENABLE ROW LEVEL SECURITY;", s.Table)
	case plan.ChangeForceRLS:
		return fmt.Sprintf("ALTER TABLE %s NO FORCE ROW LEVEL SECURITY;", s.Table)
	case plan.ChangeNoForceRLS:
		return fmt.Sprintf("ALTER TABLE %s FORCE ROW LEVEL SECURITY;", s.Table)

	case plan.ChangeCreateFunction:
		if name, args, ok := functionSignature(s.SQL); ok {
			return fmt.Sprintf("DROP FUNCTION IF EXISTS %s(%s);", name, args)
		}
		return fmt.Sprintf("-- Reversal not derivable for %s", s.Type)

	case plan.ChangeCreateAggregate:
		if name, args, ok := aggregateSignature(s.SQL); ok {
			return fmt.Sprintf("DROP AGGREGATE IF EXISTS %s(%s);", name, args)
		}
		return fmt.Sprintf("-- Reversal not derivable for %s", s.Type)

	case plan.ChangeCreateTrigger:
		trgName := ""
		if m := triggerNameRegex.FindStringSubmatch(s.SQL); len(m) == 2 {
			trgName = m[1]
		}
		return fmt.Sprintf("DROP TRIGGER IF EXISTS %s ON %s;", trgName, s.Table)

	case plan.ChangeCreateView:
		isMat := matViewRegex.MatchString(s.SQL)
		kind := "VIEW"
		if isMat {
			kind = "MATERIALIZED VIEW"
		}
		return fmt.Sprintf("DROP %s IF EXISTS %s;", kind, s.Table)

	case plan.ChangeRefreshMatView:
		// REFRESH is idempotent; refreshing again on rollback is a no-op.
		return fmt.Sprintf("-- REFRESH %s is idempotent; no reversal required", s.Table)

	case plan.ChangeCommentTable, plan.ChangeCommentColumn:
		// Restore the previous comment (IS NULL when there was none).
		escaped := strings.ReplaceAll(s.OldComment, "'", "''")
		if s.Column != "" && s.Type == plan.ChangeCommentColumn {
			return fmt.Sprintf(`COMMENT ON COLUMN "%s"."%s" IS '%s';`, s.Schema, s.Table, escaped)
		}
		return fmt.Sprintf(`COMMENT ON TABLE "%s"."%s" IS '%s';`, s.Schema, s.Table, escaped)

	default:
		return fmt.Sprintf("-- Reversal not supported for %s", s.Type)
	}
}

var (
	// policyNameRegex locates the policy name of a rendered CREATE POLICY.
	policyNameRegex = regexp.MustCompile(`(?i)CREATE\s+POLICY\s+["` + "`" + `]?([\w]+)["` + "`" + `]?\s+ON`)
	// triggerNameRegex locates the trigger name of a rendered CREATE TRIGGER.
	triggerNameRegex = regexp.MustCompile(`(?i)CREATE\s+TRIGGER\s+["` + "`" + `]?([\w]+)["` + "`" + `]?`)
	// matViewRegex detects a MATERIALIZED view create.
	matViewRegex = regexp.MustCompile(`(?i)CREATE\s+(?:OR\s+REPLACE\s+)?MATERIALIZED\s+VIEW`)
)

// functionSignature extracts the qualified name and identity argument list
// from a rendered CREATE [OR REPLACE] FUNCTION statement, e.g.
// `"public"."f"("a" integer)`. It returns ok=false for statements it cannot
// parse (procedures, malformed SQL).
func functionSignature(sql string) (name, args string, ok bool) {
	const kw = "FUNCTION"
	idx := strings.Index(strings.ToUpper(sql), kw)
	if idx < 0 {
		return "", "", false
	}
	rest := sql[idx+len(kw):]
	open := strings.IndexByte(rest, '(')
	if open < 0 {
		return "", "", false
	}
	name = strings.TrimSpace(rest[:open])
	if name == "" {
		return "", "", false
	}
	// Balanced-paren scan for the identity argument list.
	depth := 0
	for i := open; i < len(rest); i++ {
		switch rest[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return name, strings.TrimSpace(rest[open+1 : i]), true
			}
		}
	}
	return "", "", false
}

// aggregateSignature extracts the name and identity argument list from a
// rendered CREATE AGGREGATE statement, e.g. `CREATE AGGREGATE sum2(v bigint)`.
// The signature ends at the first balanced parenthesis pair (before the
// definition body); it returns ok=false for statements it cannot parse.
func aggregateSignature(sql string) (name, args string, ok bool) {
	const kw = "AGGREGATE"
	idx := strings.Index(strings.ToUpper(sql), kw)
	if idx < 0 {
		return "", "", false
	}
	rest := sql[idx+len(kw):]
	open := strings.IndexByte(rest, '(')
	if open < 0 {
		return "", "", false
	}
	name = strings.TrimSpace(rest[:open])
	if name == "" {
		return "", "", false
	}
	depth := 0
	for i := open; i < len(rest); i++ {
		switch rest[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return name, strings.TrimSpace(rest[open+1 : i]), true
			}
		}
	}
	return "", "", false
}
